version: '3'

services:

    elasticsearch:
        image: elasticsearch-custom
        build:
            dockerfile: "elasticsearch/Dockerfile"
            context: .
        container_name: elk-e
        ports:
            - "8080:9200"
        environment:
            - "discovery.type=single-node"
        volumes:
            - "./elasticsearch/es_data01:/usr/share/elasticsearch/data"
        networks:
            - "wecode"

    kibana:
        image: kibana:7.3.1
        environment:
            - "SERVER_HOST=0.0.0.0"
            - "ELASTICSEARCH_URL=http://elasticsearch-custom:9200"
        container_name: elk-k
        ports:
            - "8000:5601"
        networks:
            - "wecode"

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - "wecode"

volumes:
    es_data01:
        driver: local

networks:
    wecode:
        driver: bridge


        #- "./nginx/kibana..conf:/etc/nginx/conf.d/kibana.conf"
        #- "~/nginx/default.conf:/etc/nginx/conf.d/default.conf"
